const contentMap = [
  {
    keywords: ["hushh button", "Hushh Button For Customers", "Hushh Button For Brands", "Brands", "Customers"],
    url: "/products/hushhButton",
    content: "share data for personalized reccomendations , Imagine a world where shopping feels effortless and tailored just for you. Hushh Button, a powerful plugin, bridges the gap between your preferences/choices/needs/likes and your favourite brands , Seamless Data Sharing for Personalized Experiences , Hushh is your one-stop solution for seamless data sharing between you and your favorite websites. With Hushh, you can effortlessly share your personal data with brands to enhance your browsing experience and receive tailored recommendations , Sync your preferences, past purchases, sizing information to brands with a single click , Get your brand-specific data sent directly to your Hushh Wallet for secure storage and management , Brands can offer products and services based on your unique profile, leading to a more relevant shopping experience , Hushh Button for brands , Access authentic data from Hushh users who opt-in, allowing for personalized product recommendations and marketing campaigns , Simplified data collection and ensures compliance with user privacy preferences , Create a more personalized and rewarding shopping experience that drives loyalty and sales , Customers enjoy a seamless and personalized shopping experience, while brands gain valuable insights and build stronger relationships with their audience , Transformed Shopping Experience , With the Hushh Widget, websites and apps seamlessly change to showcase products that align with the user's preferences. It's like having a personalized shopping assistant that curates recommendations based on their unique style , Hush Button Magic , The widget allows users to create their cookies and control what information they want to share with different websites. This gives users complete control over their data privacy while enjoying a personalized shopping experience , Data Retrieval Made Easy , The widget allows users to create their cookies and control what information they want to share with different websites. This gives users complete control over their data privacy while enjoying a personalized shopping experience ",
    showRecommentationContentHeading:'Hushh Button',
    showRecommentationContentDescription: 'share data for personalized reccomendations',
  },
  {
    keywords: [" Hushh Wallet App", "Customer user flow + Client Advisor User flow", "Data Wallet", "AI" , "YOUR PERSONAL DATA"],
    url:"/products/hushhWalletApp",
    content: "Higher perk adoption, instant expense management, simple benefits access and much more , World's first AI Powered Data Wallet , Your Personal Data , Your OWN Business , Imagine a world where your data works for you, not against you. A world where your online and offline interactions paint a detailed picture of your unique self, accessible only by you and those you choose to trust. This is the reality unlocked by Hushh Wallet, the app that puts you in control of your digital identity and empowers you to reap the rewards it holds. , Scattered Data, Unified Identity , Every brand you interact with, every click you make, every purchase you complete leaves a digital footprint. Your personality, preferences, buying power, and interests are scattered across phones, platforms, and brands, often inaccessible and invisible to you. Hushh Wallet bridges this gap. It aggregates your data from various sources, including , Phone data ,Text messages, location, images, emails, call records, documents, videos, notes, etc , Data companies , Shopping brands , Online e-commerce sites, apps, and offline receipts , With Hushh, you become the curator of your own identity. You choose what information to include, building a comprehensive profile that reflects your true self , More Than Just an App , Hushh Wallet is more than just an app; it's a paradigm shift. It empowers you to , Take ownership of your digital identity , Build meaningful connections , Unlock the true potential of your data , Receipt radar , Personalized Experiences , Rewarded Interactions , Gone are the days of irrelevant ads and generic recommendations. Hushh allows you to create data cards containing specific information you're comfortable sharing. Now, you can , Connect with brands and sales agents you trust , Share your curated data cards with businesses you choose, enabling them to offer personalized experiences and recommendations tailored to your unique preferences , Get rewarded for sharing data , Earn rewards for the valuable information you contribute, be it discounts, exclusive offers, or early access to products , Sell your data , You can sell your data directly to brands and agencies, receiving fair compensation for its value , Transparency and Control , Hushh prioritizes your privacy and control. You have full transparency over who has access to your data and what they can see. You can easily revoke access or modify your data cards at any time , Enter a world made for you , Download Hushh Wallet today and unlock the power of your personal data , ",
    showRecommentationContentHeading:'Hushh Wallet App',
    showRecommentationContentDescription: "World's First AI Powered Data Wallet",
  }

];

export default contentMap;
